const theme = {
    colors: {
        landingCnt: "#B4BBB8",
        landingText: "#2D3627",
        primaryBlue: "#146C60"
    },
    images: {
        landingImg: require('./images/landing-img.png'),
        loginImg: require('./images/login-img.png'),
        registerImg: require('./images/register-img.png'),
        passwordImg: require('./images/password-img.png'),
        blurRectangle: require('./images/blur-rectangle.png'),
        menuIcon: require('./images/menu-icon.png'),
        cloudIcon: require('./images/cloud.png'),
        profileIcon: require('./images/profile.png'),
        searchIcon: require('./images/search-icon.png'),
        moreIcon: require('./images/more-icon.png'),
        photoIcon: require('./images/photo-icon.png'),
        shareIcon: require('./images/share-icon.png'),
        scanIcon: require('./images/scan-icon.png'),
        weatherBg: require('./images/home-weather-bg.png'),
        chedi_1: require('./images/chedi-1.png'),
        homeFocused: require('./images/home-focused.png'),
        communityFocused: require('./images/community-focused.png'),
        bookMarkFocused: require('./images/bookMark-focused.png'),
        cropFocused: require('./images/crop-focused.png'),
        home: require('./images/home.png'),
        community: require('./images/community.png'),
        bookMark: require('./images/bookMark.png'),
        crop: require('./images/crop.png'),
        post: require('./images/post-img.png'),
        plantBg: require('./images/plant-bg-1.png'),
        Ruler: require('./images/Ruler.png'),
        Drop: require('./images/Drop.png'),
        Sun: require('./images/Sun.png'),
        location: require('./images/location.png'),
        locationWhite: require('./images/location-white.png'),
        cloudImg: require('./images/cloud-img.png'),
        weatherPageBg: require('./images/weather-page-bg.png'),
        cropTest_1: require('./images/crop-test-1.png'),
        Temprature: require('./images/Temprature.png'),
        Planted_Gif: require('./images/planting.gif')
    },
}

export default theme;